#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 363B done
#2 DONE 0.0s

#3 [internal] load metadata for public.ecr.aws/lambda/python:3.10
#3 DONE 0.2s

#4 [1/3] FROM public.ecr.aws/lambda/python:3.10@sha256:aadd3686a174b5e54733b9862abedd9c1469c8317fd7cc1ada4e38b17d58ead3
#4 CACHED

#5 [internal] load build context
#5 transferring context: 28B done
#5 DONE 0.0s

#6 [2/3] RUN pip install --trusted-host 35.173.218.46:8081 --extra-index-url http://admin:admin@http://35.173.218.46:8081/repository/pypi/simple/ hailstone_calculator --target /var/task
#6 0.823 Looking in indexes: https://pypi.org/simple, http://admin:****@http://35.173.218.46:8081/repository/pypi/simple/
#6 0.861 WARNING: The repository located at http is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host http'.
#6 0.876 Collecting hailstone_calculator
#6 0.896   Downloading hailstone_calculator-0.0.19.tar.gz (1.5 kB)
#6 0.909   Preparing metadata (setup.py): started
#6 1.202   Preparing metadata (setup.py): finished with status 'done'
#6 1.258 Installing collected packages: hailstone_calculator
#6 1.259   DEPRECATION: hailstone_calculator is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
#6 1.259   Running setup.py install for hailstone_calculator: started
#6 1.604   Running setup.py install for hailstone_calculator: finished with status 'done'
#6 1.607 Successfully installed hailstone_calculator-0.0.19
#6 1.608 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 1.700 WARNING: The repository located at http is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host http'.
#6 1.718 
#6 1.718 [notice] A new release of pip is available: 23.0.1 -> 23.3.2
#6 1.718 [notice] To update, run: pip install --upgrade pip
#6 DONE 1.8s

#7 [3/3] COPY app.py /var/task
#7 DONE 0.1s

#8 exporting to image
#8 exporting layers 0.1s done
#8 writing image sha256:615b52b47a896c86b32e56ce828fbd28acb76a298bbc956bdb3c827e85073cb1 done
#8 naming to docker.io/library/hailstone_calculator:latest done
#8 DONE 0.1s
